name: Unit Tests
permissions:
  contents: read

on:
  push:
    branches: ['main', 'major', 'minor', 'patch']
  pull_request:
    branches: ['main', 'major', 'minor', 'patch']

jobs:
  build:
    name: Build & Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Install pnpm
        uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '22'

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      - name: Run tests
        run: node --run test
