name: Codi unit tests
permissions:
  contents: read

on:
  push:
    branches: ['main', 'major', 'minor', 'patch']
  pull_request:
    branches: ['main', 'major', 'minor', 'patch']

jobs:
  build:
    name: Build & Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: pnpm install

      - name: Run tests
        run: node --run test
